/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { CbzChapter } from './cbzChapter'
import type { PageId } from './pageId'

export interface CbzExportMetadata {
  /** Maps chapter titles to the ID of the page where the chapter begins. */
  chapters: CbzChapter[]
  coverPage?: null | PageId
}
